src/server/index.ts
src/server/interfaces/IUser.ts
src/server/models/user.ts
webpack.config.js

Changed:
- production port to 3000
- development port to 9000
Also:
- added barebones user model/schema

Port change

---

src/server/route/endpoints/auth.ts
src/server/route/endpoints/user.ts
src/server/route/path.ts
src/server/route/router.ts
src/server/warehouse/initializers/check.ts
src/server/warehouse/initializers/logger.ts
src/server/warehouse/middlewares/authUser.ts
src/server/warehouse/middlewares/bcrypt.ts

- Improved TS typing
- Improved console logging of REST requests
- Improved some syntax styling

Minor improvements

---

src/client/Components/Login/Login.tsx
src/client/Interfaces/IAction.ts
src/client/Interfaces/IReducers.ts
src/client/Store/Reducers/appReducer.ts
src/client/Store/actions.ts
src/server/warehouse/middlewares/jwtCreator.ts

- Moved interface code from Login component and appReducer to interface files
- Store username to the store upon login
- Correctly deconstruct userId from res.locals at jwtCreator

Interface cleanup, store update

---

package.json
src/client/Components/Login/Register.tsx
src/server/index.ts
webpack.config.js

- Correctly served index.html in backend with catch all for refresh bug for production mode
- Added historyApiFallback in webpack config for devServer to fix refresh bug for development mode

Refresh fix

---

src/server/index.ts
src/server/route/endpoints/user.ts
src/server/services/jwt.ts
src/server/warehouse/middlewares/authUser.ts
src/server/warehouse/middlewares/bcrypt.ts
src/server/warehouse/middlewares/jwtCreator.ts
src/server/warehouse/middlewares/jwtVerify.ts

1. Still need to build out refresh token if verified token is within grace period
1. PUT: still needs to be built out
2. Fixed param [0] colon bug
Overall: Need to handle more potential edge cases

Basic JWT Functionality Complete

---

src/client/Components/App.tsx
src/client/Components/Home/Home.tsx
src/client/Components/Home/NavBar.tsx

- Restricted endpoints at login page and corrected NavBar text

Minor fixes

---

src/client/Components/Home/NavBar.tsx
src/client/Components/Login/Login.tsx
src/client/Components/Login/Register.tsx
src/client/Components/Login/styles.css
src/client/Components/Settings/Settings.tsx

- Implemented enter key down events for inputs in login and register components
- Optimized error messages for missing inputs or invalid credentials in login and register components

Quality of life changes

---

src/client/Components/App.tsx
src/client/Components/Cards/Cluster.tsx
src/client/Components/Cards/styles.css
src/client/Components/Home/Home.tsx
src/client/Components/Home/NavBar.tsx
src/client/Components/Home/styles.css
src/client/Components/Login/Login.tsx
src/client/Components/Login/Register.tsx
src/client/Interfaces/IAction.ts
src/client/Interfaces/IReducers.ts
src/client/Store/Reducers/appReducer.ts
src/client/Store/Reducers/index.ts
src/client/Store/Reducers/navBarReducer.ts
src/client/Store/Reducers/userReducer.ts
src/client/Store/actionTypes.ts
src/client/Store/actions.ts

- Implemented navReducer to handle title text change on NavBar
- Title text for navBar changes back to initial value on refresh so have redirects to home page if initial value is detected
- Changed appReducer naming to userReducer and moved username text on home page to NavBar
- Added cluster component with base info ready with hooks to set data for cluster later

Code cleanup, navReducer, Cluster component

---

src/client/Components/Home/Home.tsx
src/client/Components/Home/UserWelcome.tsx

Created simple banner component to welcome user on the homepage.

userwelcome added

---

src/client/Components/App.tsx
src/client/Components/Cards/Cluster.tsx
src/client/Components/Home/Home.tsx
src/client/Components/Home/NavBar.tsx
src/client/Components/Login/Login.tsx
src/client/Store/Reducers/navBarReducer.ts

- Verifies JWT at each route to check if it is expired besides NavBar dropdown now when not in the login or register page

JWT token verify

---

src/client/Components/Settings/Settings.tsx

Added delete user password error message

Password error message

---

src/server/config.ts
src/server/interfaces/ICluster.ts
src/server/interfaces/IConfig.ts
src/server/models/cluster.ts
src/server/models/index.ts
src/server/mongoDb.ts
src/server/route/endpoints/auth.ts
src/server/route/endpoints/cluster.ts
src/server/route/endpoints/user.ts
src/server/route/index.ts
src/server/route/path.ts
src/server/warehouse/initializers/check.ts
src/server/warehouse/middlewares/authUser.ts
src/server/warehouse/middlewares/jwtVerify.ts

- Can now add cluster connection data and personalized cluster data to database
- Can now modify user data within user settings
- Miscellaneous codebase cleanups

Added cluster information storage and user put

---

package.json
src/server/route/endpoints/prom.ts
src/server/route/index.ts
src/server/route/path.ts

- Feed cluster id, namespace, and query to '/prom' endpoint

Built backend for promql

---

src/client/Queries/clusterPromQL.ts
src/client/Queries/nodePromQL.ts
src/client/Queries/podPromQL.ts

- Offload secure information from frontend to backend as security feature
-  @rich9029 will complete refactoring

Refactoring frontend promql query handling

---

src/server/route/endpoints/auth.ts
src/server/warehouse/middlewares/authUser.ts

- This will allow user to favorite clusters

Added userId to return object

---

src/client/Queries/containerPromQL.ts
src/client/Queries/nodePromQL.ts
src/client/Queries/podPromQL.ts

Completed PromQL queries for pod and container metrics:
- podPromQL
- containerPromQL

Completed PromQL queries

---

src/client/Components/Cards/Cluster.tsx
src/client/Components/Home/Home.tsx
src/client/Interfaces/ICluster.ts
src/client/Queries/clusterPromQL.ts
src/client/Queries/nodePromQL.ts

- Dynamically render current clusters from database
- Memory is still undefined  possibly wrong query input
- Added some cluster metrics for each cluster

Cluster Metrics feature

---

src/client/Components/Cards/Cluster.tsx
src/client/Queries/Cluster.ts
src/client/Queries/Container.ts
src/client/Queries/Node.ts
src/client/Queries/Pod.ts
src/client/Queries/index.ts
src/client/Services/index.ts
src/client/index.tsx
src/client/utils.ts

- Cleaned up formatting for promQL queries folder

Fixed formatting

---

src/client/Queries/Cluster.ts
src/client/Queries/Container.ts
src/client/Queries/Node.ts
src/client/Queries/Pod.ts
src/client/Services/Query.ts
src/client/Services/index.ts

- Created Query service to improve DRYness of query fetches

Made queries more DRY

---

src/client/Queries/Container.ts
src/client/Queries/Node.ts
src/client/Queries/Pod.ts

- Some queries lacked error handling; added try/catches

Added error handling

---

src/client/Components/Cards/Cluster.tsx
src/client/Components/Cards/styles.css
src/client/Components/Home/Home.tsx
src/client/Components/ITheme.tsx

Added cluster styling and table for cluster metrics

Added Cluster Styling

---

README.md
src/client/Components/Admin/Admin.tsx
src/client/Components/Admin/styles.css
src/client/Components/Login/Login.tsx
src/client/Components/Login/Register.tsx
src/client/Interfaces/IReducers.ts

- Deleting user now removes itself from favorites for clusters
- Update user details now has error prompts and empty input edge cases
- Experimenting with README

Squashing more bugs

---

src/client/Components/Cards/Kube.tsx
src/client/Components/Home/Home.tsx
src/client/Components/Login/Register.tsx

- Favorited clusters now rerender to top of list
- Store userId upon signup

Cluster favorites rerender

---

src/client/Components/App.tsx
src/client/Components/Cards/Kube.tsx
src/client/Components/Cards/Module.tsx
src/client/Components/Cards/styles.css
src/client/Components/Home/NavBar.tsx
src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/CustomQuery.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/client/Components/Modules/Visualizer.tsx
src/client/Components/Modules/styles.css
src/client/Interfaces/ICluster.ts

- Added routing to fullscreen module

More UI Fixes

---

src/client/Components/Admin/Admin.tsx
src/client/Components/Cards/Kube.tsx
src/client/Components/Cards/Module.tsx
src/client/Components/Cards/styles.css
src/client/Components/Home/Home.tsx
src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/styles.css
src/client/Interfaces/ICluster.ts

- Added inputs for updating cluster info and displays current info
- Error handling on edge cases for inputs
- Minor fix for rerendering name and description on container
- Added another edge case for adding clusters with regex for port numbers being numbers only
- Experimenting module rendering with buttons

Update cluster functionality

---

package.json
src/client/Components/Admin/styles.css
src/client/Components/Cards/Module.tsx
src/client/Components/Cards/styles.css
src/client/Components/Home/styles.css
src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/Visualizer.tsx
src/client/Components/Modules/styles.css
src/client/Interfaces/IGraph.ts

- Fixed rendering between mobile and desktop ratios
- Added types for React Graph

Fixed UI rendering issues and added Graph Types

---

src/client/Components/Cards/Module.tsx

- Fixed bug where making module fullscreen defaulted to OpenFaaS module rather than current module

Stateful fullscreen module

---

src/client/Components/Modules/CustomQuery.tsx
src/client/Queries/Custom.ts

Added customquery data to render on card
-conditional rendering
needs testing

Added CustomQuery data to render on the card

---

src/client/Components/Admin/Admin.tsx
src/client/Components/Home/Home.tsx
src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/server/interfaces/ICluster.ts
src/server/models/cluster.ts
src/server/route/endpoints/auth.ts
src/server/route/endpoints/cluster.ts
src/server/route/endpoints/faas.ts
src/server/route/endpoints/prom.ts
src/server/route/endpoints/user.ts
src/server/route/index.ts
src/server/route/path.ts

- Created /api/faas endpoint to handle function retrieval and deployment
- Added OpenFaaS authentication in backend
- Added OpenFaaS username and password input to frontend and MongoDB
- Still need to create endpoint to delete function and invoke function
Broken:
- Need to fix base64 encoding of 'username:password'
Co-Authored-By: xkevinle <10797460+xkevinle@users.noreply.github.com>

Added OpenFaaS Functionality

---

src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/client/Interfaces/IFunction.ts
src/server/route/endpoints/faas.ts
src/server/route/path.ts

- Fetched functions from default OpenFaaS function store and displayed with dropdown
- Implemented endpoint for invoking functions for deployed functions
- Fixed base64 encoding in backend
- Renders invoked function on OpenFaaS module on click

OpenFaaS function store deployment testing and invoking

---

src/client/Components/Cards/Kube.tsx
src/client/Components/Cards/Module.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/server/route/endpoints/auth.ts
src/server/route/endpoints/cluster.ts
src/server/route/endpoints/faas.ts
src/server/route/endpoints/prom.ts
src/server/route/endpoints/user.ts

- Can now access OpenFaaS functionality from full screen mode, as cluster id is now persistent in state
- Improved error logging on backend
- Other minor bug fixes
Co-Authored-By: xkevinle <10797460+xkevinle@users.noreply.github.com>

Fixed OpenFaaS Bugs

---

src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/server/route/endpoints/cluster.ts

- Bug fix for updating OpenFaaS credentials in cluster settings

Update OpenFaaS username/password bug fix

---

src/client/Components/Cards/Kube.tsx
src/client/Components/Cards/Module.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/client/Interfaces/IFunction.ts
src/server/route/endpoints/faas.ts

- Implemented delete button for selected deployed function
- Displays data for selected deployed function
- Invoked function now displays on text area, added request body for functions but it is non functional at the moment

OpenFaaS module 

---

src/client/Components/Admin/Admin.tsx
src/client/Components/App.tsx
src/client/Components/Cards/Kube.tsx
src/client/Components/Cards/Module.tsx
src/client/Components/Cards/styles.css
src/client/Components/Home/Home.tsx
src/client/Components/Home/NavBar.tsx
src/client/Components/Login/Login.tsx
src/client/Components/Login/Register.tsx
src/client/Components/Login/styles.css
src/client/Components/Modules/Charts.tsx
src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/CustomQuery.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/client/Components/Modules/Visualizer.tsx
src/client/Components/Modules/styles.css
src/client/Interfaces/IAction.ts
src/client/Interfaces/IReducers.ts
src/client/Queries/Cluster.ts
src/client/Store/Reducers/apiReducer.ts
src/client/Store/Reducers/clusterReducer.ts
src/client/Store/Reducers/index.ts
src/client/Store/Reducers/uiReducer.ts
src/client/Store/actionTypes.ts
src/client/Store/actions.ts

- The team began converting state management away from primarily prop drilling towards utilizing redux reducers
- We are moving towards finalizing the UI/UX design for the first official release of VaaS
To continue:
- Implementation of Redux
To add:
- More visualization interfaces
All members contributed equally:
@xkevinle @murad-alqadi @irvinie @rich9029

Big Update 

---

src/client/Components/Cards/Kube.tsx
src/client/Components/Cards/Module.tsx
src/client/Components/Cards/styles.css
src/client/Components/Modules/Charts.tsx
src/client/Components/Modules/ClusterSettings.tsx
src/client/Components/Modules/CustomQuery.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/client/Components/Modules/styles.css

Final UI Cleanup

---

src/client/Components/Cards/Module.tsx
src/client/Components/Modules/OpenFaaS.tsx
src/client/Components/Modules/Visualizer.tsx

Final commit launch day

---

src/client/Components/Cards/Kube.tsx
src/client/Components/Home/Home.tsx
src/client/Components/Modules/Visualizer.tsx
src/client/Interfaces/IAction.ts
src/client/Queries/Node.ts

- Added another fetch to allow pods to render for each namespace

Visualizer pods fix
